<?php
$title = 'List news';
$this->headTitle($title);
?>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Add news</th>
    </tr>
    <?php foreach ($paginator as $news) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($news->getTitle());?></td>
            <td><?php echo $this->escapeHtml($news->getContent());?></td>
            <td>
                <a href="<?php echo $this->url('news', array('action' => 'edit', 'id' => $news->getId()));?>"><?php echo $this->translate("Edit") ?></a>
                <a href="<?php echo $this->url('news', array('action' => 'delete', 'id' => $news->getId()));?>"><?php echo $this->translate("Delete") ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
