<?php echo $this->doctype();  ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('doc title'));  ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');  ?>
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css'); ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js', 'text/javascript');?>
    </head>
    <body>
        <table border="1" cellspacing="0" cellspadding="0" width="100%">
            <tr>
                <td>header</td>
            </tr>
            <tr><td><?php echo $this->content; ?></td></tr>
            <tr><td>footer</td></tr>
        </table>
    </body>
</html>
